#!/bin/bash
set -euo pipefail

echo "[INFO] Cài đặt Watchtower để tự động cập nhật container Docker..."

# Tạo container watchtower
docker run -d \
  --name watchtower \
  --restart=always \
  -v /var/run/docker.sock:/var/run/docker.sock \
  containrrr/watchtower \
  --cleanup \
  --interval 3600
