#!/bin/bash
set -euo pipefail

echo "=== [SETUP] Khởi chạy Docker containers ==="

# ==== Cài Docker nếu chưa có ====
if ! command -v docker &> /dev/null; then
  echo "[INFO] Docker chưa có -> Cài đặt..."
  sudo yum update -y || true
  sudo yum install -y docker -y
  sudo systemctl enable docker
  sudo systemctl start docker
fi

# ==== Xóa container cũ nếu có ====
docker rm -f tm repocket earnfm packetsdk1 ur 2>/dev/null || true

# ==== Traffmonetizer ====
docker pull traffmonetizer/cli_v2:latest
docker run -d --restart always --name tm traffmonetizer/cli_v2:latest start accept --token JoaF9KjqyUjmIUCOMxx6W/6rKD0Q0XTHQ5zlqCEJlXM=

# ==== Repocket ====
docker pull repocket/repocket:latest
docker run -d --restart=always --name repocket -e RP_EMAIL="nguyenvinhson000@gmail.com" -e RP_API_KEY="cad6dcce-d038-4727-969b-d996ed80d3ef" repocket/repocket:latest

# ==== EarnFM ====
docker pull earnfm/earnfm-client:latest
docker run -d --restart=always --name earnfm -e EARNFM_TOKEN="50f04bbe-94d9-4f6a-82b9-b40016bd4bbb" earnfm/earnfm-client:latest

# ==== PacketSDK ====
docker run -d --restart unless-stopped --name packetsdk1 packetsdk/packetsdk -appkey=BFwbNdFfwgcDdRmj

# ==== URNetwork ====
docker run -d --restart=always --cap-add NET_ADMIN --name ur -e USER_AUTH="nguyenvinhcao123@gmail.com" -e PASSWORD="CAOcao123CAO@" ghcr.io/techroy23/docker-urnetwork:2025.8.11-701332070@sha256:61caa277f928d3bd12649d55eb30cc7aa6f430c233819277dae9dbd3d5ed0bcc

echo "=== [DONE] Containers đã chạy xong ==="
docker ps -a --format "table {{.Names}}\t{{.Image}}\t{{.Status}}"
