#!/bin/bash
set -euo pipefail

echo "[INFO] Thực hiện reboot ngay (Amazon Linux 2023 / Amazon Linux 2 / CentOS 9)..."

if [ "$(id -u)" -ne 0 ]; then
  echo "[WARN] Không phải root -> dùng sudo"
  sudo /sbin/reboot
else
  /sbin/reboot
fi
